// types/database.ts
// Full TypeScript types for the Growth Marketing Problem Finder database.
// Matches 001_initial_schema.sql exactly.

// ============================================================
// Enum types (mirror CHECK constraints)
// ============================================================

export type Plan = "trial" | "starter" | "pro" | "enterprise";
export type UserRole = "owner" | "admin" | "salesperson";

export type ScanStatus =
  | "queued"
  | "running"
  | "synthesizing"
  | "completed"
  | "failed"
  | "partial";

export type ScanPhase =
  | "foundation"
  | "enrichment"
  | "email_monitoring"
  | "synthesis"
  | "done";

export type PrimitiveType =
  | "traffic_analysis"
  | "website_cro"
  | "website_technical"
  | "website_messaging"
  | "content_presence"
  | "tracking_analytics"
  | "meta_ads"
  | "google_ads"
  | "email_analysis"
  | "competitor_context"
  | "company_enrichment"
  | "brand_reputation"
  | "social_organic"
  | "pricing_monetization"
  | "meo_analysis"
  | "agent_native";

export type PrimitiveStatus =
  | "pending"
  | "running"
  | "success"
  | "error"
  | "timeout"
  | "skipped";

export type DeviceType = "desktop" | "mobile";

export type SignupStatus =
  | "pending"
  | "form_found"
  | "signed_up"
  | "failed"
  | "no_form";

export type ProblemImpact = "critical" | "high" | "medium" | "low";

// ============================================================
// Typed JSONB structures
// ============================================================

export type LoomScriptSection = {
  sectionNumber: number;
  title: string;
  say: string;
  show: string | { type: "screenshot" | "url"; ref: string; label: string };
  keyStat?: string;
  duration?: string;
};

export type LoomScript = {
  sections: LoomScriptSection[];
  totalDuration: string;
  prospectName: string;
  domain: string;
};

export type RankedProblem = {
  rank: number;
  category: string; // camelCase from LLM (e.g. "trafficAnalysis")
  title: string;
  description: string;
  impact: ProblemImpact;
  // Five C's fields (generated by LLM synthesis)
  data_point?: string;
  opportunity?: string;
  criteria?: string;
  confidence_level?: string;
  consequence?: string;
  corrective_action?: string;
  screenshotId?: string;
  screenshotIds?: string[];
  // ICE score (Impact x Confidence x Ease, 1-10 each)
  ice?: { impact: number; confidence: number; ease: number; score: number; quick_win?: boolean };
};

export type EmailAnalysis = {
  emailCount: number;
  platformDetected: string | null;
  hasWelcomeSeries: boolean;
  averageFrequency: string | null;
  subjectLines: string[];
  findings: string[];
};

export type ScreenshotMetadata = {
  fileSize?: number;
  format?: string;
  capturedAt?: string;
  [key: string]: unknown;
};

// ============================================================
// Table row types
// ============================================================

export type OrganizationRow = {
  id: string;
  name: string;
  slug: string;
  plan: Plan;
  settings: Record<string, unknown>;
  created_at: string;
  updated_at: string;
};

export type UserRow = {
  id: string;
  org_id: string;
  full_name: string | null;
  role: UserRole;
  created_at: string;
  updated_at: string;
};

export type ProspectRow = {
  id: string;
  org_id: string;
  url: string;
  domain: string;
  company_name: string | null;
  industry: string | null;
  expires_at: string | null;
  created_at: string;
  updated_at: string;
};

export type ScanRow = {
  id: string;
  org_id: string;
  prospect_id: string;
  submitted_by: string | null;
  status: ScanStatus;
  phase: ScanPhase | null;
  progress: number;
  started_at: string | null;
  completed_at: string | null;
  error_message: string | null;
  cost_usd: number;
  report_ready: boolean;
  email_report_ready: boolean;
  deep_analysis: boolean;
  expires_at: string | null;
  created_at: string;
  updated_at: string;
};

export type PrimitiveResultRow = {
  id: string;
  scan_id: string;
  primitive: PrimitiveType;
  status: PrimitiveStatus;
  data: Record<string, unknown>;
  confidence: number;
  confidence_factors: string[];
  reasoning: string | null;
  model_used: string | null;
  tokens_used: number;
  cost_usd: number;
  duration_ms: number | null;
  error_message: string | null;
  started_at: string | null;
  completed_at: string | null;
  created_at: string;
};

export type ScreenshotRow = {
  id: string;
  scan_id: string;
  storage_path: string;
  label: string;
  device_type: DeviceType;
  viewport_width: number | null;
  viewport_height: number | null;
  page_url: string | null;
  metadata: ScreenshotMetadata;
  created_at: string;
};

export type AuditOpinion = "Sound" | "Qualified" | "Deficient" | "Incomplete";

export type ReportRow = {
  id: string;
  scan_id: string;
  org_id: string;
  biggest_problem: string | null;
  biggest_problem_category: string | null;
  outreach_message: string | null;
  outreach_message_raw: string | null;
  loom_script: LoomScript | null;
  ranked_problems: RankedProblem[] | null;
  audit_opinion: AuditOpinion | null;
  dimension_categories: Record<string, unknown> | null;
  synthesis_model: string | null;
  synthesis_tokens: number | null;
  synthesis_cost_usd: number | null;
  version: number;
  created_at: string;
  updated_at: string;
};

export type EmailMonitoringRow = {
  id: string;
  scan_id: string;
  inbox_id: string | null;
  inbox_email: string | null;
  signup_status: SignupStatus;
  signup_url: string | null;
  email_platform_detected: string | null;
  emails_received: number;
  last_checked_at: string | null;
  monitoring_until: string | null;
  analysis: EmailAnalysis | null;
  created_at: string;
  updated_at: string;
};

export type ActivityLogRow = {
  id: string;
  org_id: string;
  user_id: string | null;
  scan_id: string | null;
  action: string;
  details: Record<string, unknown>;
  created_at: string;
};

// ============================================================
// Insert types (omit server-generated fields)
// ============================================================

export type OrganizationInsert = Omit<
  OrganizationRow,
  "id" | "created_at" | "updated_at"
> & {
  id?: string;
  plan?: Plan;
  settings?: Record<string, unknown>;
};

export type UserInsert = Omit<UserRow, "created_at" | "updated_at"> & {
  role?: UserRole;
};

export type ProspectInsert = Omit<
  ProspectRow,
  "id" | "created_at" | "updated_at" | "company_name" | "industry" | "expires_at"
> & {
  id?: string;
  company_name?: string | null;
  industry?: string | null;
  expires_at?: string | null;
};

export type ScanInsert = {
  org_id: string;
  prospect_id: string;
  id?: string;
  submitted_by?: string | null;
  status?: ScanStatus;
  phase?: ScanPhase | null;
  progress?: number;
  started_at?: string | null;
  completed_at?: string | null;
  error_message?: string | null;
  cost_usd?: number;
  report_ready?: boolean;
  email_report_ready?: boolean;
  deep_analysis?: boolean;
  expires_at?: string | null;
};

export type PrimitiveResultInsert = Omit<
  PrimitiveResultRow,
  "id" | "created_at"
> & {
  id?: string;
  status?: PrimitiveStatus;
  data?: Record<string, unknown>;
  confidence?: number;
  confidence_factors?: string[];
  tokens_used?: number;
  cost_usd?: number;
};

export type ScreenshotInsert = Omit<ScreenshotRow, "id" | "created_at"> & {
  id?: string;
  metadata?: ScreenshotMetadata;
};

export type ReportInsert = Omit<
  ReportRow,
  "id" | "created_at" | "updated_at"
> & {
  id?: string;
  version?: number;
};

export type EmailMonitoringInsert = Omit<
  EmailMonitoringRow,
  "id" | "created_at" | "updated_at"
> & {
  id?: string;
  signup_status?: SignupStatus;
  emails_received?: number;
};

export type ActivityLogInsert = Omit<ActivityLogRow, "id" | "created_at"> & {
  id?: string;
  details?: Record<string, unknown>;
};

// ============================================================
// Update types (all fields optional except id)
// ============================================================

export type OrganizationUpdate = Partial<
  Omit<OrganizationRow, "id" | "created_at" | "updated_at">
>;

export type UserUpdate = Partial<
  Omit<UserRow, "id" | "org_id" | "created_at" | "updated_at">
>;

export type ProspectUpdate = Partial<
  Omit<ProspectRow, "id" | "org_id" | "created_at" | "updated_at">
>;

export type ScanUpdate = Partial<
  Omit<ScanRow, "id" | "org_id" | "created_at" | "updated_at">
>;

export type PrimitiveResultUpdate = Partial<
  Omit<PrimitiveResultRow, "id" | "scan_id" | "created_at">
>;

export type ScreenshotUpdate = Partial<
  Omit<ScreenshotRow, "id" | "scan_id" | "created_at">
>;

export type ReportUpdate = Partial<
  Omit<ReportRow, "id" | "scan_id" | "org_id" | "created_at" | "updated_at">
>;

export type EmailMonitoringUpdate = Partial<
  Omit<
    EmailMonitoringRow,
    "id" | "scan_id" | "created_at" | "updated_at"
  >
>;

// Share tokens for public report links
export type ShareTokenRow = {
  id: string;
  scan_id: string;
  org_id: string;
  token: string;
  expires_at: string;
  created_at: string;
};

export type ShareTokenInsert = {
  scan_id: string;
  org_id: string;
  id?: string;
  token?: string;
  expires_at?: string;
};

// Per-org API keys
export type OrgApiKeyRow = {
  id: string;
  org_id: string;
  key_hash: string;
  key_prefix: string;
  name: string;
  scopes: string[];
  rate_limit_per_hour: number;
  last_used_at: string | null;
  expires_at: string | null;
  created_by: string | null;
  created_at: string;
  revoked_at: string | null;
};

export type OrgApiKeyInsert = {
  org_id: string;
  key_hash: string;
  key_prefix: string;
  name?: string;
  scopes?: string[];
  rate_limit_per_hour?: number;
  expires_at?: string | null;
  created_by?: string | null;
};

export type OrgApiKeyUpdate = Partial<
  Pick<OrgApiKeyRow, "name" | "scopes" | "rate_limit_per_hour" | "last_used_at" | "expires_at" | "revoked_at">
>;

// Scan opt-out registry
export type ScanOptoutRow = {
  id: string;
  domain: string;
  requested_at: string;
  requested_by_email: string | null;
  reason: string | null;
};

export type ScanOptoutInsert = Omit<ScanOptoutRow, "id" | "requested_at"> & {
  id?: string;
  requested_at?: string;
};

// activity_log is append-only — no update type needed

// ============================================================
// Supabase Database interface
// ============================================================

export type Database = {
  public: {
    Tables: {
      organizations: {
        Row: OrganizationRow;
        Insert: OrganizationInsert;
        Update: OrganizationUpdate;
        Relationships: [];
      };
      users: {
        Row: UserRow;
        Insert: UserInsert;
        Update: UserUpdate;
        Relationships: [
          {
            foreignKeyName: "users_org_id_fkey";
            columns: ["org_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      prospects: {
        Row: ProspectRow;
        Insert: ProspectInsert;
        Update: ProspectUpdate;
        Relationships: [
          {
            foreignKeyName: "prospects_org_id_fkey";
            columns: ["org_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      scans: {
        Row: ScanRow;
        Insert: ScanInsert;
        Update: ScanUpdate;
        Relationships: [
          {
            foreignKeyName: "scans_org_id_fkey";
            columns: ["org_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "scans_prospect_id_fkey";
            columns: ["prospect_id"];
            isOneToOne: false;
            referencedRelation: "prospects";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "scans_submitted_by_fkey";
            columns: ["submitted_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      primitive_results: {
        Row: PrimitiveResultRow;
        Insert: PrimitiveResultInsert;
        Update: PrimitiveResultUpdate;
        Relationships: [
          {
            foreignKeyName: "primitive_results_scan_id_fkey";
            columns: ["scan_id"];
            isOneToOne: false;
            referencedRelation: "scans";
            referencedColumns: ["id"];
          },
        ];
      };
      screenshots: {
        Row: ScreenshotRow;
        Insert: ScreenshotInsert;
        Update: ScreenshotUpdate;
        Relationships: [
          {
            foreignKeyName: "screenshots_scan_id_fkey";
            columns: ["scan_id"];
            isOneToOne: false;
            referencedRelation: "scans";
            referencedColumns: ["id"];
          },
        ];
      };
      reports: {
        Row: ReportRow;
        Insert: ReportInsert;
        Update: ReportUpdate;
        Relationships: [
          {
            foreignKeyName: "reports_scan_id_fkey";
            columns: ["scan_id"];
            isOneToOne: true;
            referencedRelation: "scans";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reports_org_id_fkey";
            columns: ["org_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      email_monitoring: {
        Row: EmailMonitoringRow;
        Insert: EmailMonitoringInsert;
        Update: EmailMonitoringUpdate;
        Relationships: [
          {
            foreignKeyName: "email_monitoring_scan_id_fkey";
            columns: ["scan_id"];
            isOneToOne: false;
            referencedRelation: "scans";
            referencedColumns: ["id"];
          },
        ];
      };
      share_tokens: {
        Row: ShareTokenRow;
        Insert: ShareTokenInsert;
        Update: Partial<Omit<ShareTokenRow, "id" | "created_at">>;
        Relationships: [
          {
            foreignKeyName: "share_tokens_scan_id_fkey";
            columns: ["scan_id"];
            isOneToOne: false;
            referencedRelation: "scans";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "share_tokens_org_id_fkey";
            columns: ["org_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      org_api_keys: {
        Row: OrgApiKeyRow;
        Insert: OrgApiKeyInsert;
        Update: OrgApiKeyUpdate;
        Relationships: [
          {
            foreignKeyName: "org_api_keys_org_id_fkey";
            columns: ["org_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      scan_optouts: {
        Row: ScanOptoutRow;
        Insert: ScanOptoutInsert;
        Update: Partial<Omit<ScanOptoutRow, "id">>;
        Relationships: [];
      };
      activity_log: {
        Row: ActivityLogRow;
        Insert: ActivityLogInsert;
        Update: Record<string, never>;
        Relationships: [
          {
            foreignKeyName: "activity_log_org_id_fkey";
            columns: ["org_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "activity_log_scan_id_fkey";
            columns: ["scan_id"];
            isOneToOne: false;
            referencedRelation: "scans";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Functions: {
      auth_org_id: {
        Args: Record<string, never>;
        Returns: string;
      };
    };
    Views: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};
